# Generated by Django 2.2.3 on 2019-08-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190813_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='type',
            field=models.CharField(choices=[('screenshot', 'screenshot'), ('main', 'main'), ('card', 'card')], default='screenshot', max_length=20),
        ),
    ]
